/**
 * Every user-facing tracker string that could be read as medical, safety or
 * promotional wording. Reviewed for compliance before launch; change here,
 * not in components. Plain English, UK spelling, no diagnosis, no product
 * claims, no treatment advice.
 */

export const CONSENT_VERSION = "2026-09-30.1";

export const copy = {
  consent: {
    title: "Before you start tracking",
    intro:
      "The tracker keeps a private record of your UTIs so you can see your own history and share it with a GP or clinic if you choose. It records what you tell it and nothing more.",
    trackerText:
      "I consent to Utee storing the symptoms, triggers, treatments, tests and notes I log in the tracker. This is health information. It is stored in the UK, only I can see it, and I can export or delete it at any time from the tracker settings. My chats with Una, the tracker helper, are kept with my record so I can reopen them. What I type to Una is sent to Utee's AI provider only to fill in the form, and I can turn that off and tap the options instead.",
    trackerLabel: "I agree to Utee storing my tracker entries",
    researchTitle: "Optional: help research",
    researchText:
      "I also consent to Utee using my tracker entries, with anything that could identify me removed, in combined figures for research and reporting. This is optional and I can switch it off at any time.",
    researchLabel: "Use my anonymised entries for research (optional)",
    separateNote:
      "This is separate from the consent you give when you use a Utee test. You can withdraw either at any time in settings.",
    button: "Start tracking",
  },

  aboutMe: {
    title: "About you",
    intro:
      "A few questions asked once, so you don't have to answer them every time. You can change them later in settings.",
    pregnantHint: "If yes, we'll show safety information whenever you log a new UTI.",
    preventiveTitle: "Are you taking anything to help prevent UTIs?",
    preventiveHint: "Choose everything that applies. You can change this any time. Nothing here is a recommendation.",
    button: "Save and continue",
  },

  redFlag: {
    title: "Please get medical help today",
    body:
      "Some of what you've logged can need prompt attention. Contact your GP today, or call NHS 111. If you feel very unwell, call 999.",
    pregnancyBody:
      "Because you've told us you are pregnant or trying, please contact your GP or midwife today about these symptoms, or call NHS 111. If you feel very unwell, call 999.",
    footnote: "This is safety information only. The tracker does not tell you what is causing your symptoms.",
  },

  dashboard: {
    welcomeTitle: "Your UTI tracker",
    welcomeBody:
      "Log each UTI as it happens and build a record you can show a GP or clinic. You can also add ones you remember from the past.",
    logFirst: "Log your first UTI",
    logPast: "Add a past UTI",
    openEpisodeDay: (day: number) => `Day ${day} of this UTI`,
    logToday: "Log today",
    editToday: "Edit today",
    openEpisodeLink: "Open this UTI",
    seeHistory: "See full history",
    feelBetter: "I feel better",
    sinceLast: (days: number) =>
      days === 0 ? "Your last UTI ended today" : `${days} day${days === 1 ? "" : "s"} since your last UTI ended`,
    logNew: "Log a UTI",
    lastYear: "My last 12 months",
    patterns: "My patterns",
    patternsEmpty: "Once you've logged a few UTIs, this card will show which triggers and symptoms you log most, and how you rated each antibiotic.",
    tests: "My tests",
    testsEmpty: "Any Utee test you take will show here with its status.",
    history: "History",
    quickActions: "Quick actions",
    downloadSummary: "Download GP summary",
    orderTest: "Order a Utee test",
    orderTestNote: "Available any time. Not a recommendation based on what you've logged.",
    community: "Utee community",
    communityBody: "Talk with other people who understand. Opens in a new tab.",
    prevention: "What I'm taking",
    preventionEmpty: "Nothing logged yet. Add anything you take to help prevent UTIs, so your record shows what you've tried and what you feel helps.",
    preventionManage: "Manage",
    preventionAdd: "Add what I'm taking",
    preventionHelps: "helps",
    quickAdd: "Talk to Una",
  },

  guided: {
    name: "Una",
    title: "Guided setup",
    titleQuick: "Add UTIs quickly",
    titlePrevention: "Update what I'm taking",
    intro: "Hi, I'm Una, your Utee tracker helper. I'll set up your tracker with a few short questions. Just answer in your own words. I only fill in your record. I don't give medical advice.",
    introQuick: "Hi, it's Una. Tell me about your UTIs in your own words and I'll fill in the record for you to check.",
    introFree: "Hi, it's Una. Tell me about a UTI, something you've started or stopped taking, or both, and I'll fill in your record for you to check.",
    askFree: "What would you like to add or update?",
    anythingElse: "Done. Anything else?",
    nudgeHelping: (name: string) => `Quick one. You've had ${name} on your list for a few weeks. Is it helping?`,
    nudgeThanks: "Thanks, noted.",
    bubbleOpen: "Chat with Una",
    bubbleClose: "Close",
    aiCaveat: "Una uses AI to read what you type. You can switch this off in Settings.",
    aiCaveatOff: "AI reading is off. Una matches plain phrases only.",
    askAbout: "First, a bit about you. Are you before, around or after the menopause? Do you use contraception? Are you pregnant or trying?",
    askPrevention: "Do you take anything to help prevent UTIs? For example something you take each day, vaginal oestrogen, a vaccine, or a cream or spray.",
    askUtis: "Now your UTIs, one or several. For each, roughly when it started and ended, what you noticed, what you took and whether it helped. Or say \"none yet\".",
    askUtisQuick: "Tell me about a UTI, or several at once. Roughly when it started and ended, what you noticed, what you took and whether it helped. Or say \"none\".",
    gotIt: "Here's what I picked up. Check it and change anything that's wrong.",
    addedToCard: "Added that below. Change it if it's not right.",
    askPreventionUpdate: "What are you taking now to help prevent UTIs, and has anything stopped? I'll update your list.",
    savedPreventionUpdate: (added: number, stopped: number) =>
      added === 0 && stopped === 0 ? "Noted. Your list is unchanged." : [added ? `added ${added}` : "", stopped ? `stopped ${stopped}` : ""].filter(Boolean).join(" and ").replace(/^./, (c) => c.toUpperCase()) + ".",
    askChangedTaking: "Has anything changed in what you take to prevent UTIs?",
    askMoreUtis: "Any UTIs to add?",
    yes: "Yes",
    noDone: "No, I'm done",
    resume: "Picking up where we left off. Anything to add?",
    update: {
      ack: "Sorry it's still hanging around. Let's get today logged.",
      ackCalm: "Let's get today logged.",
      feeling: "How are you feeling today?",
      symptoms: "What are you noticing today?",
      overview: "Here's today's log. Save it, or change something.",
      line: (date: string) => `Today, on your UTI from ${date}`,
      feelingLine: "Feeling",
      noticingLine: "Noticing",
      triggerLine: "Possible trigger added",
      noteLine: "Note",
      saved: (date: string) => `Saved to your UTI from ${date}.`,
      noOpen: "I can't see an open UTI on your record. If this is a new one, tell me when it started and I'll add it.",
    },
    close: {
      glad: "Glad it's cleared. When did it clear up?",
      noOpen: "I can't see an open UTI on your record. If you'd like to add one that's now over, tell me when it started and ended.",
      openCheck: (date: string) => `Your UTI from ${date} is still open on your record. Has it cleared up?`,
      overview: "Here's what I'll record. Save it, or change the date.",
      line: (date: string, ended: string) => `UTI from ${date}: ended ${ended}`,
      saved: (date: string) => `Done. Your UTI from ${date} is closed.`,
      changeDate: "Change the date",
    },
    talk: "Talk to Una",
    history: "History",
    historyEmpty: "No chats yet.",
    newChat: "New chat",
    backToChat: "Back",
    openChat: "Open",
    untitledChat: "Chat with Una",
    ask: {
      menopause: "Are you before, around or after the menopause? You can say \"rather not say\".",
      contraception: "Do you use contraception? For example the pill, a coil, condoms, or none.",
      pregnant: "Are you currently pregnant or trying?",
      aboutOverview: "Here's what I have. Save it, or change something.",
      started: "When did it start? For example \"yesterday\", \"last Tuesday\" or \"12 September\".",
      ended: "Has it cleared up, or is it still going?",
      endedOn: "When did it end?",
      symptoms: "What did you notice? For example burning, needing to go often, cloudy or smelly urine, blood, pain.",
      triggers: "Anything that might have set it off? For example sex, not drinking enough, a hot bath. Or say \"not sure\".",
      treatment: "Did you take anything for it, like an antibiotic? Tell me the name, or say \"no\".",
      days: "How many days was the course?",
      worked: (name: string) => `Did the ${name} help?`,
      tests: "Did you have a test for it? For example a dipstick at home or the pharmacy, a sample sent off, or a Utee test. Or say \"no\".",
      overview: "Here's the overview. Save it, or tell me what to change.",
      change: "What would you like to change? Say which part, for example \"the start date\" or \"the antibiotic\".",
      preventionOverview: "Here's what I'll update. Save it, or tell me what's different.",
      preventionPick: "Tell me what you take, in your own words.",
    },
    chips: {
      done: "Done",
      skip: "Skip",
      nothing: "Nothing",
      nothingChanged: "Nothing's changed",
      chooseFromList: "Choose from the list",
      noAntibiotics: "No antibiotics",
      noTest: "No test",
      dontKnow: "Don't know",
      save: "Save",
      change: "Change something",
      remove: (name: string) => `Remove ${name}`,
    },
    overview: {
      started: "Started",
      ended: "Ended",
      stillGoing: "Still going",
      noticed: "Noticed",
      triggers: "Possible triggers",
      antibiotics: "Antibiotics",
      tests: "Tests",
      notes: "Notes",
      none: "None",
      nothingNoted: "Nothing noted",
      helped: "helped",
      adding: "Adding",
      stopping: "Stopping",
      unchanged: "No changes",
      menopause: "Menopause",
      contraception: "Contraception",
      pregnant: "Pregnant or trying",
    },
    followUp: {
      wasTaking: (name: string) => `Were you still taking your ${name} when it started?`,
      wasTakingNote: (name: string, answer: string) => `Still taking ${name} when it started: ${answer}`,
      notSure: "Not sure",
      ended: "Has it cleared up now, or is it still going?",
      treatment: "Did you take anything for it, like an antibiotic?",
      worked: (name: string) => `Did the ${name} help?`,
      tests: "Did you have a test for it? At home, at the GP or pharmacy, or a Utee test?",
      noAntibiotics: "No antibiotics",
      noTest: "No test",
      dontRemember: "Don't remember",
    },
    gotSeveral: (n: number) => `I picked up ${n} UTIs. Check each one and change anything that's wrong.`,
    gotNothing: "I didn't catch that. You can tell me about a UTI, how today is going, or something you've started or stopped taking.",
    thinking: "Reading that...",
    savedAbout: "Saved. Thank you.",
    savedPrevention: (n: number) => (n === 0 ? "Noted. Nothing added for now." : `Saved ${n} thing${n === 1 ? "" : "s"} to what you're taking.`),
    savedUti: (date: string) => `Saved the UTI from ${date}.`,
    anotherQ: "Another UTI to add?",
    another: "Add another",
    allDone: "That's all",
    skip: "Skip for now",
    noneYet: "None yet",
    done: "All set. Your tracker is ready.",
    doneQuick: "Done. Everything you added is in your history.",
    goDashboard: "Go to my tracker",
    goHistory: "See my history",
    next: "Next",
    saveUti: "Save this UTI",
    discardUti: "Don't save this one",
    send: "Send",
    placeholder: "Type here...",
    tapInstead: "Add one step by step",
    preferForm: "Prefer a form?",
    startNeeded: "Choose when it started.",
    fields: {
      started: "When did it start?",
      ended: "Has it ended?",
      stillGoing: "Still going",
      over: "It's over",
      endedOn: "When did it end?",
      symptoms: "What did you notice?",
      triggers: "Anything that might have set it off?",
      treatments: "Antibiotics",
      tests: "Tests",
      notes: "Notes",
      days: "days",
      worked: "Did it help?",
      addTreatment: "Add an antibiotic",
      addTest: "Add a test",
      remove: "Remove",
      kind: "What kind of test?",
      result: "Result",
    },
  },

  prevention: {
    title: "What I'm taking",
    intro: "Everything you take to help prevent UTIs, and whether you feel it helps. Only you can say. This is your record, not advice.",
    current: "Taking now",
    past: "Tried before",
    nothingYet: "Nothing here yet.",
    add: "Add something",
    addButton: "Add",
    since: (date: string) => `Since ${date}`,
    between: (from: string | null, to: string) => (from ? `${from} to ${to}` : `Until ${to}`),
    startDate: "When did you start?",
    helping: "Is it helping?",
    helpingHint: "Only you can say. Kept for your own record.",
    notes: "Notes",
    stop: "I've stopped this",
    restart: "Start again",
    remove: "Remove",
    whichAntibiotic: "Which antibiotic?",
    otherLabel: "Other, name it",
    groupNote: "Groups are for finding things quickly. Nothing here is a recommendation.",
    edit: "Edit",
    updateByChat: "Talk to Una",
    searchPlaceholder: "Search, for example D-mannose, Hiprex, oestrogen",
    searchNone: (q: string) => `Nothing called "${q}" in the list.`,
    addAsOther: (q: string) => `Add "${q}"`,
    browse: "Or browse the list",
  },

  patterns: {
    trigger: (label: string, times: number, of: number) => `${label}: logged in ${times} of ${of} UTIs`,
    antibiotic: (name: string, worked: number, rated: number) =>
      `${name}: you said it worked ${worked} of ${rated} time${rated === 1 ? "" : "s"}`,
    symptom: (label: string, times: number, of: number) => `${label}: ${times} of ${of} UTIs`,
    ofUtis: (of: number) => `of ${of} UTIs`,
    triggersTitle: "What you noted before a UTI",
    symptomsTitle: "What you noticed most",
    antibioticsTitle: "How you rated each antibiotic",
    helpedOf: (worked: number, rated: number) => `helped ${worked} of ${rated}`,
    tipsTitle: "Ideas that fit your patterns",
    tipsTitleGeneral: "A few ideas people find useful",
    tipsNote: "General information in plain words, not advice for you. Talk to your GP or pharmacist before changing anything.",
    readMore: (name: string) => `Read more at ${name}`,
  },

  log: {
    title: "Log a UTI",
    when: "When did it start?",
    symptoms: "What are you noticing?",
    symptomsPast: "What did you notice?",
    stillGoing: "Is it still going?",
    ongoing: "Still going",
    over: "It's over",
    whenEnded: "When did it end?",
    sameAsLast: "Same as last time",
    save: "Save",
    triggers: "Anything that might have set it off?",
    treatment: "Treatment",
    tests: "Tests",
    notes: "Notes",
    feeling: "How are you feeling today?",
    closeEpisode: "I feel better now",
    closed: (date: string) => `Ended ${date}`,
    reopen: "Reopen",
    didItWork: "Did it work?",
    didItWorkHint: "Only you can say. This is kept for your own record.",
    courseHint: "Choose the length your prescriber gave you.",
    uteeTestLinked: "Linked to your Utee test in the portal.",
    uteeTestLink: "Link a Utee test",
    uteeTestNone: "You don't have a Utee test to link yet.",
  },

  episode: {
    back: "Tracker",
    title: "Your UTI",
    started: (date: string, day: number) => `Started ${date} · Day ${day}`,
    ended: (date: string, days: number) => `Ended ${date} · ${days} day${days === 1 ? "" : "s"}`,
    feelBetter: "I feel better",
    reopen: "Reopen",
    closedNote: "This UTI is closed. You can still add to it or reopen it.",
    menu: "More actions",
    delete: "Delete this UTI",
    deleteConfirmTitle: "Delete this UTI?",
    deleteConfirmBody: "Everything logged for it will be permanently removed. This cannot be undone.",
    deleteConfirmButton: "Yes, delete it",
    cancel: "Cancel",
    changeStart: "Change start date",
    today: (date: string) => `Today, ${date}`,
    feelingQuestion: "How are you feeling?",
    noticingQuestion: "What are you noticing today?",
    sameAsYesterday: "Same as yesterday",
    saved: "Saved",
    aboutTitle: "About this UTI",
    add: "Add",
    edit: "Edit",
    editing: "Editing below",
    remove: "Remove",
    done: "Done",
    rows: {
      symptoms: "What you noticed",
      triggers: "Possible triggers",
      treatment: "Treatment",
      tests: "Tests",
      notes: "Notes",
    },
    addNote: "Add a note",
    addAnotherAntibiotic: "Add another antibiotic",
    addAntibiotic: "Add an antibiotic",
    addTest: "Add a test",
    yoursBefore: "Yours before",
    showAll: "Show all",
    willAskOn: (date: string) => `We'll ask how it went on ${date}`,
    willAskOnClose: "We'll ask how it went when you close this UTI",
    askToday: "We'll ask how it went in your check-in today",
    howDidItGo: (name: string) => `How did ${name} go?`,
    downloadSummary: "Download GP summary",
    whenBetter: "When did you start feeling better?",
  },

  antibiotics: {
    search: "Search by name or brand",
    previous: "Ones you've logged before",
    noMatch: "No match. Choose Other and type the name.",
    otherLabel: "Name",
    groupNote: "Groups are for finding things quickly. Nothing here is a recommendation.",
  },

  settings: {
    title: "Tracker settings",
    export: "Export my data",
    exportBody: "Everything in your tracker, as a file you keep.",
    exportJson: "Download JSON",
    exportCsv: "Download CSV",
    delete: "Delete my tracker data",
    deleteBody:
      "Permanently deletes every UTI, symptom, treatment, test, note and check-in you've logged, and your tracker consents. This cannot be undone. Your portal account and any Utee tests are not affected.",
    deleteConfirm: "Type DELETE to confirm",
    deleteButton: "Delete everything",
    reminders: "Reminders",
    remindersBody:
      "Optional emails from Utee. They never mention symptoms or UTIs in the subject line or body.",
    reminderDaily: "A daily check-in while a UTI is open",
    reminderMonthly: "A monthly nudge to log anything I've missed",
    una: "Una",
    unaBody: "Una reads what you type so she can fill in your record. With AI reading on, your message is sent to Utee's AI provider only for that. With it off, she matches plain phrases and may miss things.",
    unaAi: "Let Una use AI to read my messages",
    consents: "Consents",
    consentTracker: "Storing my tracker entries",
    consentResearch: "Anonymised research use",
    consentWithdrawNote:
      "Withdrawing tracker consent stops the tracker. To remove your data as well, use Delete my tracker data.",
    aboutMe: "About you",
  },

  reminders: {
    chatButton: "Update what you're taking by chat",
    dailySubject: "Your Utee check-in",
    dailyBody:
      "You asked us to remind you to check in. Open your tracker whenever you have a moment.",
    monthlySubject: "A quick note from Utee",
    monthlyBody:
      "You asked for a monthly reminder. If there's anything you'd like to add to your tracker, it's ready when you are.",
    button: "Open my tracker",
  },

  pdf: {
    prevention: "Prevention, as reported by the patient",
    title: "My UTI history",
    footer: "Recorded by the patient using the Utee tracker. Not a clinical record.",
    generated: (date: string) => `Generated ${date}`,
    range: (from: string, to: string) => `${from} to ${to}`,
    noEpisodes: "No UTIs recorded in this period.",
    uteeTest: "Utee test",
    reportInPortal: "Clinical report available in the Utee portal",
  },

  history: {
    title: "My UTI history",
    empty: "Nothing logged yet.",
    ongoing: "Ongoing",
    days: (n: number) => `${n} day${n === 1 ? "" : "s"}`,
  },
};
