-- The patient report is now generated by the portal rather than uploaded.
-- The clinic edits the results wording (a manual override when the sheet
-- shows heavy contamination), signs it electronically and publishes. The
-- content and the signatures applied are kept with the report so the PDF
-- can be regenerated and audited.
alter table clinic_reports
  add column if not exists content jsonb,
  add column if not exists signatures jsonb not null default '[]',
  add column if not exists generated_at timestamptz;

-- A clinician's saved signature: drawn once, applied to each report they
-- sign. The image lives in the private 'signatures' bucket.
create table if not exists staff_signatures (
  user_id uuid primary key references profiles (id) on delete cascade,
  display_name text not null,
  title text,
  organisation text,
  image_path text not null,
  updated_at timestamptz not null default now()
);
alter table staff_signatures enable row level security;

insert into storage.buckets (id, name, public)
values ('signatures', 'signatures', false)
on conflict (id) do nothing;
